sudo: required
services:
  - docker
  - redis-server
language: node_js
node_js:
  - "9"
before_install:
  - npm i -g npm@latest
install:
  - docker build -t sigwotechnologies/metis:latest ./
script:
  - docker run --name metis sigwotechnologies/metis:latest npm run test
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push sigwotechnologies/metis:latest